# Generated by Django 4.1.3 on 2022-11-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 21, 12, 19, 11, 317874), verbose_name='Опубликована'),
        ),
    ]
