# Generated by Django 4.1.3 on 2022-11-21 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 21, 12, 53, 26, 166889), verbose_name='Опубликована'),
        ),
    ]
